# Nord theme for Alacritty

# Colors (Nord)
[colors.primary]
background = "#2E3440"  # nord0
foreground = "#D8DEE9"  # nord4

[colors.cursor]
text = "#2E3440"       # nord0
cursor = "#D8DEE9"     # nord4

[colors.vi_mode_cursor]
text = "#2E3440"       # nord0
cursor = "#D8DEE9"     # nord4

[colors.selection]
text = "#2E3440"       # nord0
background = "#4C566A"  # nord3

[colors.search.matches]
foreground = "#2E3440"       # nord0
background = "#88C0D0"       # nord8

[colors.search.focused_match]
foreground = "#2E3440"       # nord0
background = "#8FBCBB"       # nord7

[colors.normal]
black = "#3B4252"   # nord1
red = "#BF616A"     # nord11
green = "#A3BE8C"   # nord14
yellow = "#EBCB8B"  # nord13
blue = "#81A1C1"    # nord9
magenta = "#B48EAD"  # nord15
cyan = "#88C0D0"    # nord8
white = "#D8DEE9"   # nord4

[colors.bright]
black = "#4C566A"   # nord3
red = "#BF616A"     # nord11 (often kept same or slightly brighter, Nord doesn't have distinct brights for these)
green = "#A3BE8C"   # nord14
yellow = "#EBCB8B"  # nord13
blue = "#81A1C1"    # nord9
magenta = "#B48EAD"  # nord15
cyan = "#8FBCBB"    # nord7 (using a slightly different Frost color for bright cyan)
white = "#ECEFF4"   # nord6
